name: RodPulling
description: RodPulling plugin for Dev
author: D3m0n0id
version: 1.0
main: com.cubekrowd.net.Main

commands:
  fdrag:
    description: Main plugin syntax.
    usage: /fdrag <value>
  fdrag add:
    description: Adds a player to the "Server Admin" list.
    usage: /fdrag add <name>
  fdrag remove:
    description: Removes a player from the "Server Admin" list.
    usage: /fdrag remove <name>
  fdrag on:
    description: Turns the plugin on.
    usage: /fdrag on
  fdrag off:
    description: Turns the plugin off.
    usage: /fdrag off
  fdrag mult:
   description: Changes the player's velocity when using the plugin.
   usage: /fdrag mult <value>
